dataset: edflow.datasets.fashionmnist.FashionMNISTTrain
validation_dataset: edflow.datasets.fashionmnist.FashionMNISTTest
model: template_pytorch.edflow.Model
iterator: template_pytorch.edflow.Iterator
batch_size: 4
num_epochs: 2

n_classes: 10
