datasets:
  train: edflow.datasets.fashionmnist.FashionMNISTTrain
  validation: edflow.datasets.fashionmnist.FashionMNISTTest
model: template_pytorch.edflow.Model
iterator: template_pytorch.edflow.Iterator
batch_size: 4
num_epochs: 2

n_classes: 10


fixed_example_indices: [0, 1, 2, 3]