language: python
python:
  - 3.6
notifications:
  email: false
  
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install: true

after_success:
  - coveralls

# Run test
jobs:
  include:
    - stage: formatting
      name: "formatting test"
      install:
        - pip install black
      script:
        - black --check .
      after_success: skip
    - stage: documentation
      name: "documentation test"
      install:
        - pip install sphinx sphinx_rtd_theme sphinxcontrib-apidoc pyyaml numpy better_apidoc
      script:
        - cd docs
        - sphinx-build -W -v -b html . _build/
      after_success: skip
    - stage: tf_example_tests
      name: "Tensorflow examples test"
      install:
        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION tensorflow=1.13.1
        - source activate test-environment
        - pip install -e .[test]
      script:
        - cd examples
        - pytest --cov edflow -k tf --cov-config .coveragerc --cov-append
        - cd ..
    - stage: torch_example_tests
      name: "Pytorch examples test"
      install:
        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
        - source activate test-environment
        - conda install pytorch-cpu torchvision-cpu -c pytorch
        - pip install tensorboardX
        - pip install -e .[test]
      script:
        - cd examples
        - pytest --cov edflow -k torch --cov-config .coveragerc --cov-append
        - cd ..
    - stage: general_tests
      name: "General Tests"
      install:
        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION tensorflow=1.13.1
        - source activate test-environment
        - conda install pytorch-cpu torchvision-cpu -c pytorch
        - pip install tensorboardX
        - pip install -e .[test]
      script:
        - python -c "import skimage" # fix failing test due to static tls loading
        - pytest --cov edflow --cov-config .coveragerc --ignore=examples # use pytest instead of python -m pytest
