datasets:
  train: edflow.datasets.fashionmnist.FashionMNISTTrain
  validation: edflow.datasets.fashionmnist.FashionMNISTTest
model: template_tfe.edflow.Model
iterator: template_tfe.edflow.Iterator
batch_size: 4
num_epochs: 2

n_classes: 10
